FROM golang:1.12.0-alpine3.9 AS builder

WORKDIR /go/src/app
COPY hello.go .

RUN go get -d -v \
  && go install -v \
  && go build


FROM scratch
WORKDIR /go/src/app
COPY --from=builder /go/bin/app /go/bin/
CMD ["/go/bin/app"]


